// Enterprise Regulatory Dataset - India Jurisdiction Baseline (Private Limited Entity)

export const INITIAL_COMPANY = {
  name: "Apex Technologies Pvt Ltd",
  cin: "U72900MH2024PTC412345",
  gstin: "27AAACA1234B1Z5",
  sector: "IT Services & SaaS",
  entityType: "Private Limited Company",
  state: "Maharashtra",
  annualTurnover: "₹1.25 Crore",
  employeeCount: 18,
  incorporationDate: "2024-02-15",
  complianceScore: 84, // Overall Score
};

export const COMPLIANCE_KPI_METRICS = {
  score: 78,
  scoreBadge: "High Readiness",
  upcomingDeadlinesCount: 5, // Next 30 days
  activeRiskAlertsCount: 2, // Red alert: DIR-3 KYC
  totalObligations: 20,
  satisfiedObligations: 13,
  pendingObligations: 5,
};

export const STATUTORY_TIMELINE_ITEMS = [
  {
    id: "TL-01",
    title: "EPF Monthly ECR Filing & Statutory Deposit",
    authority: "EPFO (Employees' Provident Fund)",
    dueDate: "2026-08-15",
    type: "Recurring (Monthly)",
    status: "Amber", // Upcoming / Needs Attention
    statusText: "Due in 11 Days",
    citation: "EPF & MP Act, 1952 - Paragraph 38",
    description: "Monthly deposit of Provident Fund contributions for 18 employees.",
    assignedTo: "HR & Payroll Lead",
    evidenceFile: "EPF_ECR_Draft_Aug2026.pdf",
    cycle: "Monthly Recurring",
  },
  {
    id: "TL-02",
    title: "GSTR-3B Monthly Summary Return & Tax Payment",
    authority: "CBIC / GSTN",
    dueDate: "2026-08-20",
    type: "Recurring (Monthly)",
    status: "Amber",
    statusText: "Due in 16 Days",
    citation: "CGST Act, 2017 - Section 39 & Rule 61(5)",
    description: "Monthly return filing & tax liability settlement for July 2026.",
    assignedTo: "Tax Department",
    evidenceFile: "GSTR3B_July2026_Challan.pdf",
    cycle: "Monthly Recurring",
  },
  {
    id: "TL-03",
    title: "Form DIR-3 KYC Director Annual Verification",
    authority: "Ministry of Corporate Affairs (MCA)",
    dueDate: "2026-09-30",
    type: "Annual Recurring",
    status: "Red", // Overdue / High Risk
    statusText: "AT RISK - OTP Pending",
    citation: "Companies Director Rules, 2014 - Rule 12A",
    description: "Director 2 (Sanjay Sharma) KYC verification pending mobile OTP. Risk of DIN deactivation & ₹5,000 penalty.",
    assignedTo: "Secretarial Team",
    evidenceFile: "DIR3_KYC_Pending_Director2.pdf",
    cycle: "1-Year Cycle",
  },
  {
    id: "TL-04",
    title: "Form AOC-4: Annual Financial Statements Filing",
    authority: "MCA (Companies Act, 2013)",
    dueDate: "2026-10-30",
    type: "Annual Recurring",
    status: "Green", // Compliant
    statusText: "Satisfied (FY 2024-25)",
    citation: "Companies Act, 2013 - Section 137",
    description: "Annual balance sheet & financial statement filing with Registrar of Companies.",
    assignedTo: "External CA Auditor",
    evidenceFile: "Form_AOC4_Filing_SRN_Z98765432.pdf",
    cycle: "1-Year Cycle",
  },
  {
    id: "TL-05",
    title: "Form MGT-7: Corporate Annual Return",
    authority: "MCA (Companies Act, 2013)",
    dueDate: "2026-11-29",
    type: "Annual Recurring",
    status: "Green",
    statusText: "Satisfied (FY 2024-25)",
    citation: "Companies Act, 2013 - Section 92(4)",
    description: "Annual return of company details, shareholders, and board meetings.",
    assignedTo: "Secretarial Team",
    evidenceFile: "Form_MGT7_Ack_SRN_X12345678.pdf",
    cycle: "1-Year Cycle",
  },
  {
    id: "TL-06",
    title: "Statutory Auditor Appointment (Form ADT-1)",
    authority: "MCA (Companies Act, 2013)",
    dueDate: "2029-09-30",
    type: "5-Year Cycle",
    status: "Green",
    statusText: "Active (2024-2029)",
    citation: "Companies Act, 2013 - Section 139(1)",
    description: "5-year statutory auditor appointment tenure active.",
    assignedTo: "Board of Directors",
    evidenceFile: "Form_ADT1_SRN_A11223344.pdf",
    cycle: "Multi-Year (5-Year)",
  },
  {
    id: "TL-07",
    title: "GSTR-1 Outward Supply Return",
    authority: "CBIC / GSTN",
    dueDate: "2026-08-11",
    type: "Recurring (Monthly)",
    status: "Amber",
    statusText: "Due in 7 Days",
    citation: "CGST Act, 2017 - Section 37",
    description: "Monthly filing of outward supplies.",
    assignedTo: "Tax Department",
    evidenceFile: "GSTR1_July2026_Draft.pdf",
    cycle: "Monthly Recurring",
  },
  {
    id: "TL-08",
    title: "ITR-6 Income Tax Return",
    authority: "Income Tax Department",
    dueDate: "2026-10-31",
    type: "Annual Recurring",
    status: "Green",
    statusText: "Satisfied (FY 2025-26)",
    citation: "IT Act 1961 - Sec 139",
    description: "Annual Income Tax Return for Companies.",
    assignedTo: "External CA Auditor",
    evidenceFile: "ITR6_Ack_FY25-26.pdf",
    cycle: "1-Year Cycle",
  },
  {
    id: "TL-09",
    title: "Form MSME-1 Half Yearly Return",
    authority: "MCA",
    dueDate: "2026-10-31",
    type: "Recurring (Half-Yearly)",
    status: "Red",
    statusText: "AT RISK",
    citation: "Companies Act 2013 - Sec 405",
    description: "Return of outstanding payments to MSME vendors.",
    assignedTo: "Accounts Payable",
    evidenceFile: "MSME1_Draft_Pending.pdf",
    cycle: "6-Month Cycle",
  },
  {
    id: "TL-10",
    title: "Annual General Meeting",
    authority: "MCA",
    dueDate: "2026-09-30",
    type: "Annual Recurring",
    status: "Amber",
    statusText: "Upcoming",
    citation: "Companies Act 2013 - Sec 96",
    description: "Holding of Annual General Meeting.",
    assignedTo: "Secretarial Team",
    evidenceFile: "AGM_Notice_Draft.pdf",
    cycle: "1-Year Cycle",
  },
  {
    id: "TL-11",
    title: "Advance Tax Instalment (Q2)",
    authority: "Income Tax Department",
    dueDate: "2026-09-15",
    type: "Recurring (Quarterly)",
    status: "Green",
    statusText: "Satisfied",
    citation: "IT Act 1961 - Sec 211",
    description: "Payment of Q2 Advance Tax.",
    assignedTo: "Finance Team",
    evidenceFile: "AdvTax_Challan_Q2.pdf",
    cycle: "Quarterly Recurring",
  },
  {
    id: "TL-12",
    title: "Board Meeting Minutes Filing",
    authority: "MCA",
    dueDate: "2026-08-30",
    type: "Recurring (Quarterly)",
    status: "Green",
    statusText: "Satisfied",
    citation: "Companies Act 2013 - Sec 173",
    description: "Quarterly Board Meeting Minutes documentation.",
    assignedTo: "Secretarial Team",
    evidenceFile: "BM_Minutes_Aug26.pdf",
    cycle: "Quarterly Recurring",
  }
];

export const GITHUB_STYLE_AUDIT_FEED = [
  {
    id: "act-101",
    actor: "Tax Department Lead",
    avatar: "TD",
    action: "uploaded evidence",
    target: "Form_26Q_Q1_Ack_Receipt.pdf",
    timestamp: "12 minutes ago",
    hash: "0x8f4a9b...7c1d",
    status: "Green",
  },
  {
    id: "act-102",
    actor: "Document Extraction Agent",
    avatar: "AI",
    action: "parsed & matched rule",
    target: "IN-GST-GSTR3B-004 (CGST Act Sec 39)",
    timestamp: "45 minutes ago",
    hash: "0x3e12c9...b50a",
    status: "Green",
  },
  {
    id: "act-103",
    actor: "Compliance Head",
    avatar: "CH",
    action: "created task node",
    target: "Director 2 DIR-3 KYC Verification",
    timestamp: "2 hours ago",
    hash: "0x77c211...99e4",
    status: "Amber",
  },
  {
    id: "act-104",
    actor: "SME Legal Reviewer",
    avatar: "SME",
    action: "approved rule update",
    target: "IN-MCA-AOC4-001 (Ver 2.1)",
    timestamp: "5 hours ago",
    hash: "0x12a88f...ef33",
    status: "Green",
  },
  {
    id: "act-105",
    actor: "Temporal Orchestrator",
    action: "checkpoint logged",
    target: "Durable state transition saved",
    timestamp: "1 day ago",
    hash: "0x99b11c...44a1",
    status: "Green",
  },
];

export const REGULATORY_RULES_FULL = [
  {
    id: "IN-MCA-AOC4-001",
    title: "Form AOC-4: Annual Financial Statements Filing",
    authority: "MCA",
    citation: "Companies Act, 2013 - Section 137",
    dueDate: "2026-10-30",
    status: "Green",
    statusText: "Satisfied",
    smeApproved: true,
    smeId: "SME_LEGAL_042",
  },
  {
    id: "IN-MCA-MGT7-002",
    title: "Form MGT-7: Corporate Annual Return",
    authority: "MCA",
    citation: "Companies Act, 2013 - Section 92(4)",
    dueDate: "2026-11-29",
    status: "Green",
    statusText: "Satisfied",
    smeApproved: true,
    smeId: "SME_LEGAL_042",
  },
  {
    id: "IN-MCA-DIR3KYC-003",
    title: "Form DIR-3 KYC: Director Annual KYC",
    authority: "MCA",
    citation: "Companies Director Rules, 2014 - Rule 12A",
    dueDate: "2026-09-30",
    status: "Red",
    statusText: "AT RISK",
    smeApproved: true,
    smeId: "SME_LEGAL_019",
  },
  {
    id: "IN-GST-GSTR3B-004",
    title: "GSTR-3B: Monthly Summary Tax Return",
    authority: "CBIC / GSTN",
    citation: "CGST Act, 2017 - Section 39",
    dueDate: "2026-08-20",
    status: "Amber",
    statusText: "Pending Action",
    smeApproved: true,
    smeId: "SME_TAX_008",
  },
  {
    id: "IN-EPF-ECR-005",
    title: "EPF Monthly ECR Return & Deposit",
    authority: "EPFO",
    citation: "EPF & MP Act, 1952 - Paragraph 38",
    dueDate: "2026-08-15",
    status: "Amber",
    statusText: "Upcoming",
    smeApproved: true,
    smeId: "SME_LABOR_003",
  },
  {
    id: "IN-GST-REG-001",
    title: "GST Registration",
    authority: "CBIC / GSTN",
    jurisdiction: "Central + State",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company", "LLP"],
      annual_turnover_gt: 4000000,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "registration",
    frequency: "one_time",
    deadline_rule: "Within 30 days of crossing turnover threshold",
    penalty: "100% of tax due or ₹10,000, whichever is higher",
    citation: "CGST Act 2017, Sec 22",
    source: { doc: "CGST_Act_2017.pdf", url: "https://cbic.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_TAX_010",
    dueDate: "2024-03-15",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-GST-GSTR1-001",
    title: "GSTR-1 Outward Supply Return",
    authority: "CBIC / GSTN",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "monthly",
    deadline_rule: "11th of the succeeding month",
    penalty: "₹50 per day of delay",
    citation: "CGST Act 2017, Sec 37",
    source: { doc: "CGST_Act_2017.pdf", url: "https://cbic.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_TAX_011",
    dueDate: "2026-08-11",
    statusText: "Upcoming",
    statusColor: "Amber",
  },
  {
    id: "IN-IT-ITR6-001",
    title: "ITR-6 Income Tax Return for Companies",
    authority: "Income Tax Department",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "annual",
    deadline_rule: "October 31 of assessment year",
    penalty: "Up to ₹10,000 for late filing",
    citation: "IT Act 1961, Sec 139",
    source: { doc: "IT_Act_1961.pdf", url: "https://incometaxindia.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_TAX_012",
    dueDate: "2026-10-31",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-IT-26Q-001",
    title: "Form 26Q TDS Return - Non-salary",
    authority: "Income Tax Department",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "quarterly",
    deadline_rule: "End of month following the quarter",
    penalty: "₹200 per day of default",
    citation: "IT Act 1961, Sec 200(3)",
    source: { doc: "IT_Act_1961.pdf", url: "https://incometaxindia.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_TAX_013",
    dueDate: "2026-10-31",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-MCA-DPT3-001",
    title: "Form DPT-3 Return of Deposits",
    authority: "MCA",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "annual",
    deadline_rule: "June 30 of every year",
    penalty: "Up to ₹5,000 and ₹500 per day",
    citation: "Companies Act 2013, Sec 73, Rule 16",
    source: { doc: "Companies_Act_2013.pdf", url: "https://mca.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LEGAL_020",
    dueDate: "2026-06-30",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-MCA-ADT1-001",
    title: "Form ADT-1 Auditor Appointment",
    authority: "MCA",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "registration",
    frequency: "5_year",
    deadline_rule: "Within 15 days of AGM",
    penalty: "Standard additional fees",
    citation: "Companies Act 2013, Sec 139(1)",
    source: { doc: "Companies_Act_2013.pdf", url: "https://mca.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LEGAL_021",
    dueDate: "2029-09-30",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-MCA-BM-001",
    title: "Board Meeting Minutes Filing",
    authority: "MCA",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "quarterly",
    deadline_rule: "Within 30 days of Board Meeting",
    penalty: "₹25,000 on company and ₹5,000 on officer in default",
    citation: "Companies Act 2013, Sec 173",
    source: { doc: "Companies_Act_2013.pdf", url: "https://mca.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LEGAL_022",
    dueDate: "2026-08-30",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-ESI-REG-001",
    title: "ESI Registration & Returns",
    authority: "ESIC",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: 10,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "monthly",
    deadline_rule: "15th of the following month",
    penalty: "12% interest and damages up to 100%",
    citation: "ESI Act 1948, Sec 2(12)",
    source: { doc: "ESI_Act_1948.pdf", url: "https://esic.nic.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LABOR_004",
    dueDate: "2026-08-15",
    statusText: "Upcoming",
    statusColor: "Amber",
  },
  {
    id: "IN-PT-REG-001",
    title: "Professional Tax Registration",
    authority: "State Government (Maharashtra)",
    jurisdiction: "State",
    applicability: {
      entity_type: ["Private Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "registration",
    frequency: "annual",
    deadline_rule: "Annually as per state timeline",
    penalty: "₹50 per day for delay",
    citation: "Maharashtra State Tax on Professions Act, 1975",
    source: { doc: "PT_Act_1975.pdf", url: "https://mahagst.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_TAX_014",
    dueDate: "2026-06-30",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-MCA-INC20A-001",
    title: "Form INC-20A Business Commencement Declaration",
    authority: "MCA",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "one_time",
    deadline_rule: "Within 180 days of incorporation",
    penalty: "₹50,000 for company, ₹1,000 per day for directors",
    citation: "Companies Act 2013, Sec 10A",
    source: { doc: "Companies_Act_2013.pdf", url: "https://mca.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LEGAL_023",
    dueDate: "2024-08-15",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-MCA-MSME1-001",
    title: "Form MSME-1 Outstanding Payments",
    authority: "MCA",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "half_yearly",
    deadline_rule: "30-Apr and 31-Oct",
    penalty: "Up to ₹25,000",
    citation: "Companies Act 2013, Sec 405",
    source: { doc: "Companies_Act_2013.pdf", url: "https://mca.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LEGAL_024",
    dueDate: "2026-10-31",
    statusText: "AT RISK",
    statusColor: "Red",
  },
  {
    id: "IN-MCA-AGM-001",
    title: "Annual General Meeting",
    authority: "MCA",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "annual",
    deadline_rule: "Within 6 months from closure of FY",
    penalty: "Up to ₹1,00,000 and ₹5,000 per day",
    citation: "Companies Act 2013, Sec 96",
    source: { doc: "Companies_Act_2013.pdf", url: "https://mca.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LEGAL_025",
    dueDate: "2026-09-30",
    statusText: "Upcoming",
    statusColor: "Amber",
  },
  {
    id: "IN-MCA-MBP1-001",
    title: "Form MBP-1 Director Interest Disclosure",
    authority: "MCA",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "annual",
    deadline_rule: "First board meeting in FY",
    penalty: "Up to ₹1,00,000 and/or 1 year imprisonment",
    citation: "Companies Act 2013, Sec 184",
    source: { doc: "Companies_Act_2013.pdf", url: "https://mca.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_LEGAL_026",
    dueDate: "2026-04-30",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-IT-24Q-001",
    title: "TDS on Salary Form 24Q",
    authority: "Income Tax Department",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "quarterly",
    deadline_rule: "End of month following the quarter",
    penalty: "₹200 per day of default",
    citation: "IT Act 1961, Sec 192",
    source: { doc: "IT_Act_1961.pdf", url: "https://incometaxindia.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_TAX_015",
    dueDate: "2026-10-31",
    statusText: "Satisfied",
    statusColor: "Green",
  },
  {
    id: "IN-IT-ADVTAX-001",
    title: "Advance Tax Instalments",
    authority: "Income Tax Department",
    jurisdiction: "Central",
    applicability: {
      entity_type: ["Private Limited Company", "Public Limited Company"],
      annual_turnover_gt: null,
      employee_count_gt: null,
      sector: "any"
    },
    obligation_type: "filing",
    frequency: "quarterly",
    deadline_rule: "15th of Jun, Sep, Dec, Mar",
    penalty: "1% interest per month under Sec 234B & 234C",
    citation: "IT Act 1961, Sec 211",
    source: { doc: "IT_Act_1961.pdf", url: "https://incometaxindia.gov.in", fetched: "2026-06-01" },
    version: 1,
    status: "sme_approved",
    smeApproved: true,
    smeId: "SME_TAX_016",
    dueDate: "2026-09-15",
    statusText: "Pending Action",
    statusColor: "Amber",
  }
];

export const PENALTY_RULES_MAP = {
  "GSTR-3B": {
    authority: "CBIC / GSTN",
    citation: "CGST Act 2017 Sec 47 & Rule 61(5)",
    statuteText: "Late fee under Section 47: ₹50 per day of delay (₹25 CGST + ₹25 SGST). Maximum cap: ₹5,000 per return. Interest under Sec 50: 18% p.a. on outstanding tax liability.",
    dailyRate: 50,
    maxCap: 5000,
    escalationDays: 90,
    escalationType: "Show cause notice + 18% interest compounding"
  },
  "GSTR-1": {
    authority: "CBIC / GSTN",
    citation: "CGST Act 2017 Sec 37 & 47",
    statuteText: "Late fee of ₹50 per day of delay under Section 47. Blocking of GSTR-1 for subsequent tax periods under Rule 59(6) if GSTR-3B is defaulted.",
    dailyRate: 50,
    maxCap: 5000,
    escalationDays: 60,
    escalationType: "E-Way Bill blocking & tax credit freeze"
  },
  "DIR-3 KYC": {
    authority: "Ministry of Corporate Affairs (MCA)",
    citation: "Companies Director Rules 2014 Rule 12A",
    statuteText: "Deactivation of Director Identification Number (DIN) upon failure to file DIR-3 KYC by Sept 30. One-time late filing penalty fee of ₹5,000 per director to reactivate DIN.",
    dailyRate: 0,
    fixedFee: 5000,
    maxCap: 5000,
    escalationDays: 30,
    escalationType: "DIN deactivation & disqualification risk"
  },
  "Form AOC-4": {
    authority: "Ministry of Corporate Affairs (MCA)",
    citation: "Companies Act 2013 Sec 137(3)",
    statuteText: "Late fee of ₹100 per day of delay under Companies Act 2013. Additional fine of ₹10,000 on company and ₹100/day up to ₹50,000 on officer in default. Prosecution risk for continued default.",
    dailyRate: 100,
    maxCap: null,
    escalationDays: 270,
    escalationType: "Prosecution of directors & company strike-off notice"
  },
  "Form MGT-7": {
    authority: "Ministry of Corporate Affairs (MCA)",
    citation: "Companies Act 2013 Sec 92(5)",
    statuteText: "Late filing fee of ₹100 per day. Penalty of ₹50,000 on company plus ₹100 per day during default, subject to maximum ₹5,000,000.",
    dailyRate: 100,
    maxCap: 5000000,
    escalationDays: 270,
    escalationType: "Prosecution under Section 92(5)"
  },
  "Form 26Q": {
    authority: "Income Tax Department",
    citation: "Income Tax Act 1961 Sec 234E & 272A",
    statuteText: "Mandatory fee under Sec 234E of ₹200 per day of default until return is filed. Penalty under Sec 271H ranging from ₹10,000 to ₹100,000 if default exceeds 1 year.",
    dailyRate: 200,
    maxCap: null,
    escalationDays: 365,
    escalationType: "Prosecution under Sec 276B (up to 7 years imprisonment)"
  },
  "Form 24Q": {
    authority: "Income Tax Department",
    citation: "Income Tax Act 1961 Sec 234E",
    statuteText: "Mandatory fee under Sec 234E of ₹200 per day of default for delayed filing of employee salary TDS quarterly returns.",
    dailyRate: 200,
    maxCap: null,
    escalationDays: 365,
    escalationType: "Sec 271H penalty & prosecution"
  },
  "EPF ECR": {
    authority: "EPFO (Employees' Provident Fund)",
    citation: "EPF & MP Act 1952 Para 14B & Sec 7Q",
    statuteText: "Damages up to 100% of arrears under Para 14B plus simple interest at 12% per annum under Sec 7Q for default in payment of Provident Fund contribution.",
    dailyRate: 0,
    interestPercent: 12,
    maxCap: null,
    escalationDays: 60,
    escalationType: "Recovery proceedings & non-bailable warrant risk"
  },
  "ITR-6": {
    authority: "Income Tax Department",
    citation: "Income Tax Act 1961 Sec 234F",
    statuteText: "Late filing fee of ₹5,000 under Sec 234F if filed after due date (₹10,000 if filed after Dec 31). Interest under Sec 234A at 1% per month on unpaid tax.",
    dailyRate: 0,
    fixedFee: 5000,
    maxCap: 10000,
    escalationDays: 180,
    escalationType: "Best judgment assessment & loss set-off forfeiture"
  },
  "INC-001": {
    authority: "MCA",
    citation: "Companies Act 2013 Sec 7",
    statuteText: "One-time incorporation filing. Default causes failure to incorporate.",
    dailyRate: 0,
    maxCap: 0,
    escalationDays: 30,
    escalationType: "Registration rejection"
  },
  "LAB-001": {
    authority: "Labour Department",
    citation: "Shops and Establishments Act",
    statuteText: "Late fee of ₹50 per day for delayed renewal of Labour License.",
    dailyRate: 50,
    maxCap: 5000,
    escalationDays: 60,
    escalationType: "License suspension & establishment closure notice"
  }
};

